name: Automate Workflow
on:
  push:
    branches: [ main ]

jobs:
  unit-test:
    name: Run unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '19'
      - name: Run unit tests
        uses: ./gradlew test

