name: Automate Workflow
on:
  push:
    branches: [ main ]

jobs:
  linter:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup java
        uses: action/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Run linter
        run: ./gradlew spotlessCheck
  unit-test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    needs:
      - linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Run Unit Tests
        run: ./gradlew test
  build:
    name: Build Java
    runs-on: ubuntu-latest
    needs:
      - linter
      - unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build java
        run: ./gradlew build